services:
  figranium:
    build:
      context: .
      args:
        INSTALL_VNC: ${INSTALL_VNC}
        PLAYWRIGHT_BROWSERS: ${PLAYWRIGHT_BROWSERS}

    ports:
      - "${APP_PORT}:11345"
      - "${VNC_PORT}:54311"

    environment:
      NODE_ENV: ${NODE_ENV}
      DOPPELGANGER_SKIP_PLAYWRIGHT_INSTALL: ${DOPPELGANGER_SKIP_BROWSER_DOWNLOAD}
      PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: ${PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD}

      SESSION_COOKIE_SECURE: ${SESSION_COOKIE_SECURE}
      TRUST_PROXY: ${TRUST_PROXY}
      SESSION_SECRET: ${SESSION_SECRET}

    volumes:
      - ${DATA_DIR}:/app/data

    restart: unless-stopped
